### PR TITLE
Update assignment.json

### PR DESCRIPTION
**Pull request by izendegi**
Hi,

It's not clear for me what are those 4 assignment types, this proposal is more clear for me (if you refer to those assignment types).

### CODE REVIEW

**Comment by martignoni** [comment]
Re: assignment types, see: https://docs.moodle.org/39/en/Assignment_activity#Assignment_.28Submission.29_types

**Comment by izendegi** [comment]
Hi Nicolas,

After reading the docs still don't know what those 4 types are, because there are different settings (submission types, group submission settings...) and could be combined in several ways. I guess that you refer only to the different combination of the "submission types" settings (File submissions & Online text)?

I wrote this because I thought it could be a inheritance from the types of the [old assignment module](https://docs.moodle.org/22/en/Assignment_module), and that's why I've proposed the change, but it was only a suggestion :-)

**Comment by martignoni** [comment]
You're right: we should write "two types" instead of "four". Would you please amend your PR with just this change?

**Comment by martignoni** [comment]
I've made the change (see commit 22ade5148775b5619bd3034857c8ac5afda3fe26). Thanks for the suggestion.

**Pull request closed without merging**
